# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022



steps:
- pwsh: |
    $version = [regex]::matches($(rustdoc --version), "\d+\.\d+\.\d+").Value
    echo "Rustdoc $version"
    $version = [regex]::matches($(cargo --version), "\d+\.\d+\.\d+").Value
    echo "Cargo $version"
    $rustVersion = [regex]::matches($(rustc --version), "\d+\.\d+\.\d+").Value
    echo "Rustup $version"
    "Rust $version"

    echo $(Get-BindgenVersion)
    echo $(Get-CargoAuditVersion)
    echo $(Get-CargoOutdatedVersion)
    echo $(Get-CbindgenVersion)
    echo "Rustfmt $(Get-RustfmtVersion)"
    echo "Clippy $(Get-RustClippyVersion)"

    echo "Rust $(Get-RustVersion)"
    echo "Rustup $(Get-RustupVersion)"
    echo "Cargo $(Get-RustCargoVersion)"
    echo "Rustdoc $(Get-RustdocVersion)"

