# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022



steps:
- pwsh: |
    $version = [regex]::matches($(rustdoc --version), "\d+\.\d+\.\d+").Value
    echo "Rustdoc $version"
    $version = [regex]::matches($(cargo --version), "\d+\.\d+\.\d+").Value
    echo "Cargo $version"
    $rustVersion = [regex]::matches($(rustc --version), "\d+\.\d+\.\d+").Value
    echo "Rust $version"
    echo $(cbindgen --version)
    echo $(cargo audit --version)
    echo $(cargo outdated --version)
    $version = [regex]::matches($(cargo clippy  --version), "\d+\.\d+\.\d+").Value
    echo "clippy $version"
    $version = [regex]::matches($(rustfmt --version), "\d+\.\d+\.\d+").Value
    echo "Rustfmt $version"